name: Keebs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-dev python3-pip openjdk-11-jdk-headless x11vnc python3-numpy python3-lxml imagemagick python3-yaml subversion python3-psutil xvfb recordmydesktop xdotool xfce4 npm openssh-client kicad
        sudo pip3 install --no-compile kibot kiauto pcbdraw svg2mod
        svn co svn://svn.repo.hu/freerouting_cli/trunk && cd trunk && make && make install && cd .. && rm -rf trunk
        mkdir -p ~/.kicad/scripting/plugins
        cd ~/.kicad/scripting/plugins && git clone https://github.com/asukiaaa/gerber_to_order.git

    - name: build
      run: make || true

    - name: list
      run: ls -lah

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: "*.ogv"
        retention-days: 1
