name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag keeb
    - name: Run docker image
      run: docker run --rm -v $(pwd):/mount keeb
