name: Lasagna
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true+
          
      - name: Setup Dhall
        uses: dhall-lang/setup-dhall@v4
        
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
