name: Lasagna
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    env:
      NODE_VERSION: 16
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true+

      - name: Setup node without cache
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache
        uses: actions/cache@v2.1.7
        if: ${{ !env.ACT }}
        with:
          path:
            - ergogen/node_modules
          key: ${{ runner.os }}-${{ hashFiles('ergogen/package-lock.json') }}
          restore-keys:
            - ${{ runner.os }}-

      - name: Check dhall is installed
        id: dhall
        uses: andstor/file-existence-action@v1
        with:
          files: "bin/dhall"
                    
      - name: Setup dhall if it is not installed
        if: steps.dhall.outputs.file_exists == 'false'
        uses: dhall-lang/setup-dhall@v4
        
      - name: Environment Preparation
        run: |
          mkdir -p output
          cd ergogen
          npm i

      - name: Create ergogen config
        run: bin/dhall-to-yaml --explain --file variants/lasagna.dhall --output output/lasagna.yaml

      - name: Archive (Ergogen Config)
        uses: actions/upload-artifact@v2
        with:
          name: lasagna
          path: output/lasagna.yaml
      
      - name: Run ergogen
        run: |
          cd ergogen
          node src/cli.js -o ../output ../output/lasagna.yaml